In [3]:
import numpy as np
import tensorflow as tf
from adult_modified import preprocess_adult_data

seed = 1
dataset_orig_train, dataset_orig_test = preprocess_adult_data(seed = seed)

In [4]:
dataset_orig_test

               instance weights  features                             \
                                                                       
                                      age education-num capital-gain   
instance names                                                         
13237                       1.0 -1.175586     -1.607059    -0.147413   
23644                       1.0  0.264770     -0.435784    -0.147413   
178                         1.0 -1.554628     -0.435784    -0.147413   
16741                       1.0 -0.341696     -0.435784    -0.147413   
28620                       1.0 -0.948162     -0.435784    -0.147413   
...                         ...       ...           ...          ...   
47211                       1.0 -1.099778      1.125916    -0.147413   
35106                       1.0  0.264770      1.125916    -0.147413   
5661                        1.0 -1.478820     -2.387908    -0.147413   
13155                       1.0 -1.630436     -1.607059    -0.14

In [9]:
x_train = dataset_orig_train.features

In [1]:
from adult_experiment import *

parameter:time-20200513-134357-expt_id-771334-lr-0.0005-w_reg-1.0-l2_reg-0
Instructions for updating:
Use tf.identity instead.
Test accuracy for step 0: 0.5102266669273376

Test GAP RMS for step 0: 0.07435241989602592

Test balenced accuracy for step 0: 0.6124019920825958

Test accuracy for step 250: 0.8347153067588806

Test GAP RMS for step 250: 0.1343446198737928

Test balenced accuracy for step 250: 0.7466579042375088

Test accuracy for step 500: 0.844112753868103

Test GAP RMS for step 500: 0.08099763179749658

Test balenced accuracy for step 500: 0.7682999968528748

Test accuracy for step 750: 0.8475400805473328

Test GAP RMS for step 750: 0.07100816792763001

Test balenced accuracy for step 750: 0.7739595770835876

Final test accuracy: 0.8488667607307434

Final test GAP RMS: 0.06350603187263354

Final test balenced accuracy: 0.7629517801105976




In [2]:
x, y, group = data_test
logits = experiment.classifier(x)

In [3]:
predictions = tf.cast(tf.argmax(logits, axis = 1), dtype = tf.int32)

In [4]:
predictions

<tf.Tensor: shape=(9045,), dtype=int32, numpy=array([0, 0, 0, ..., 0, 0, 0], dtype=int32)>

In [6]:
tf.argmax(logits, axis = 1)

<tf.Tensor: shape=(9045,), dtype=int64, numpy=array([0, 0, 0, ..., 0, 0, 0])>

In [7]:
logits

<tf.Tensor: shape=(9045, 2), dtype=float32, numpy=
array([[ 1.0128586 , -1.5647669 ],
       [ 0.54416907, -0.78029585],
       [ 2.3287683 , -2.4858282 ],
       ...,
       [ 2.2926817 , -2.7051296 ],
       [ 1.9832346 , -2.3899448 ],
       [ 1.2653949 , -1.225308  ]], dtype=float32)>

In [8]:
y

<tf.Tensor: shape=(9045, 2), dtype=float32, numpy=
array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)>

In [10]:
tf.reduce_mean(y[:,1])

<tf.Tensor: shape=(), dtype=float32, numpy=0.24311775>

In [12]:
z = y[:, 1]

In [13]:
z[z == 1]

<tf.Tensor: shape=(2199,), dtype=float32, numpy=array([1., 1., 1., ..., 1., 1., 1.], dtype=float32)>

In [14]:
predictions

<tf.Tensor: shape=(9045,), dtype=int32, numpy=array([0, 0, 0, ..., 0, 0, 0], dtype=int32)>

In [15]:
predictions[predictions == 1]

<tf.Tensor: shape=(1578,), dtype=int32, numpy=array([1, 1, 1, ..., 1, 1, 1], dtype=int32)>

In [16]:
label = 1

In [17]:
predictions = tf.cast(tf.argmax(logits, axis = 1), dtype = tf.int32)
y = tf.cast(y[:, 1], dtype = tf.int32)

In [18]:
predictions_label = predictions[y == label]
group_label = group[y == label]
predictions_label0 = predictions_label[group_label == 0]
predictions_label1 = predictions_label[group_label == 1]
diff = tf.reduce_mean(predictions_label0) - tf.reduce_mean(predictions_label1)

In [19]:
diff

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [20]:
predictions_label0

<tf.Tensor: shape=(317,), dtype=int32, numpy=
array([0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
     

In [21]:
predictions_label1

<tf.Tensor: shape=(1882,), dtype=int32, numpy=array([1, 1, 1, ..., 1, 0, 1], dtype=int32)>

In [22]:
tf.reduce_mean(predictions_label1)

<tf.Tensor: shape=(), dtype=int32, numpy=0>