In [1]:
import numpy as np
import tensorflow as tf
x_train, y_train, group_train = np.random.normal(size = (10000, 39)), np.random.binomial(1, 0.5, (10000, )), np.random.binomial(1, 0.5, (10000, 2))
x_test, y_test, group_test = np.random.normal(size = (6000, 39)), np.random.binomial(1, 0.5, (6000, )), np.random.binomial(1, 0.5, (6000, 2))

In [2]:
x_train, y_train, group_train = tf.cast(x_train, tf.float32), tf.one_hot(y_train, 2), tf.cast(group_train, tf.int32)
x_test, y_test, group_test = tf.cast(x_test, tf.float32), tf.one_hot(y_test, 2), tf.cast(group_test, tf.int32)
data_train = x_train, y_train, group_train
data_test = x_test, y_test, group_test

In [3]:
import itertools
groups = list(itertools.product([0,1], [0,1]))
groups = [list(x) for x in groups]
groups = tf.cast(groups, tf.int32)

In [4]:
groups 

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]], dtype=int32)>

In [5]:
import setup2
e = setup2.GroupFairness()
e.set_graph(classifier_input_shape=(39,), n_groups=4)

In [6]:
e.create_tensorboard()

parameter:time-20200514-173229-expt_id-892473-lr-0.0001-w_reg-1.0-l2_reg-0


In [7]:
e.fit(data_train, data_test, groups)

parameter:time-20200514-173229-expt_id-419980-lr-0.0001-w_reg-1.0-l2_reg-0
Instructions for updating:
Use tf.identity instead.
Test accuracy for step 0: 0.4986666738986969

Test GAP RMS for feature 0 and step 0: 0.00015069781511556357

Test GAP RMS for feature 1 and step 0: 0.00012828434410039335

Test balanced accuracy for step 0: 0.494412899017334




In [1]:
import numpy as np
import tensorflow as tf
from adult_modified import preprocess_adult_data
import setup

# Adult data processing
seed = 1
dataset_orig_train, dataset_orig_test = preprocess_adult_data(seed = seed)

x_all_train, x_all_test = dataset_orig_train.features, dataset_orig_test.features

In [3]:
dataset_orig_train

               instance weights  features                             \
                                                                       
                                      age education-num capital-gain   
instance names                                                         
42106                       1.0  1.022853     -0.045359    -0.147413   
31714                       1.0  0.340579      1.125916    -0.147413   
10772                       1.0  0.340579      1.125916    -0.147413   
15825                       1.0 -0.493312     -0.826209    -0.147413   
40653                       1.0 -0.493312     -0.826209    -0.147413   
...                         ...       ...           ...          ...   
37008                       1.0 -0.644929     -0.045359    -0.147413   
43443                       1.0 -0.948162     -0.826209    -0.147413   
20022                       1.0 -1.327203     -0.045359    -0.147413   
43753                       1.0  0.947045      1.516340    -0.14

In [1]:
import numpy as np
import tensorflow as tf
from adult_modified import preprocess_adult_data
import setup2

# Adult data processing
seed = 1
dataset_orig_train, dataset_orig_test = preprocess_adult_data(seed = seed)

all_train, all_test = dataset_orig_train.features, dataset_orig_test.features
y_train, y_test = dataset_orig_train.labels.reshape((-1,)), dataset_orig_test.labels.reshape((-1,))
y_train, y_test = y_train.astype('int32'), y_test.astype('int32')

x_train = np.delete(all_train, [dataset_orig_test.feature_names.index(feat) for feat in ['sex_ Male', 'race_ White']], axis = 1)
x_test = np.delete(all_test, [dataset_orig_test.feature_names.index(feat) for feat in ['sex_ Male', 'race_ White']], axis = 1)

group_train = dataset_orig_train.features[:, [dataset_orig_test.feature_names.index(feat) for feat in ['sex_ Male', 'race_ White']]]
group_test = dataset_orig_test.features[:, [dataset_orig_test.feature_names.index(feat) for feat in ['sex_ Male', 'race_ White']]]

x_train, y_train, group_train = tf.cast(x_train, dtype = tf.float32),\
     tf.one_hot(y_train, 2), tf.cast(group_train, dtype = tf.int32)


x_test, y_test, group_test = tf.cast(x_test, dtype = tf.float32),\
     tf.one_hot(y_test, 2), tf.cast(group_test, dtype = tf.int32)

data_train = x_train, y_train, group_train
data_test = x_test, y_test, group_test

In [2]:
group_train

<tf.Tensor: shape=(36177, 2), dtype=int32, numpy=
array([[0, 1],
       [0, 0],
       [0, 0],
       ...,
       [0, 0],
       [1, 1],
       [1, 0]], dtype=int32)>

In [3]:
y_train

<tf.Tensor: shape=(36177, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]], dtype=float32)>

In [1]:
from adult_expt_gender_race import *

parameter:time-20200515-100228-expt_id-771334-lr-0.0001-w_reg-10.0-l2_reg-0
Instructions for updating:
Use tf.identity instead.
Test accuracy for step 0: 0.6577114462852478

Test GAP RMS for gender and step 0: 0.12050401419401169

Test GAP RMS for race and step 0: 0.049244657158851624

Test balanced accuracy for step 0: 0.5767894387245178


Test accuracy for step 250: 0.7565506100654602

Test GAP RMS for gender and step 250: 0.0030976261477917433

Test GAP RMS for race and step 250: 0.00868151430040598

Test balanced accuracy for step 250: 0.5010156035423279


Test accuracy for step 500: 0.7568822503089905

Test GAP RMS for gender and step 500: 0.0

Test GAP RMS for race and step 500: 0.0

Test balanced accuracy for step 500: 0.5


Test accuracy for step 750: 0.7568822503089905

Test GAP RMS for gender and step 750: 0.0

Test GAP RMS for race and step 750: 0.0

Test balanced accuracy for step 750: 0.5


Test accuracy for step 1000: 0.7568822503089905

Test GAP RMS for gender and step 1