In [1]:
import tensorflow as tf
from nn_graph import *

In [4]:
NN = NNGraph(architecture=[10, 20, 30, 44])

In [5]:
NN.model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
hidden-layer-1 (Dense)       (None, 10)                410       
_________________________________________________________________
hidden-layer-2 (Dense)       (None, 20)                220       
_________________________________________________________________
hidden-layer-3 (Dense)       (None, 30)                630       
_________________________________________________________________
logit-layer (Dense)          (None, 44)                1364      
Total params: 2,624
Trainable params: 2,624
Non-trainable params: 0
_________________________________________________________________


In [6]:
a = [[1,2], [2,3], [3, 4]]
a = tf.cast(a, dtype=tf.float32)


In [9]:
tf.linalg.normalize(a, ord = 1, axis = 1)

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.33333334, 0.6666667 ],
        [0.4       , 0.6       ],
        [0.42857143, 0.5714286 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 1), dtype=float32, numpy=
 array([[3.],
        [5.],
        [7.]], dtype=float32)>)

In [1]:
import setup
import numpy as np
import tensorflow as tf

In [2]:
data_train = tf.random.normal((1000, 40)), tf.one_hot(np.random.binomial(1, 0.5, 1000), 2), \
tf.cast(np.random.binomial(1, 0.5, 1000), dtype=tf.float32)
data_test = tf.random.normal((1000, 40)), tf.one_hot(np.random.binomial(1, 0.5, 1000), 2), \
tf.cast(np.random.binomial(1, 0.5, 1000), dtype=tf.float32)

In [3]:
expt = setup.GroupFairness()

In [4]:
expt.set_graph()

In [5]:
expt.classifier.model.summary()

Model: "classifier"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
hidden-layer-1 (Dense)       (None, 10)                410       
_________________________________________________________________
hidden-layer-2 (Dense)       (None, 20)                220       
_________________________________________________________________
logit-layer (Dense)          (None, 2)                 42        
Total params: 672
Trainable params: 672
Non-trainable params: 0
_________________________________________________________________


In [6]:
expt.potential_y0[0].model.summary()

Model: "potential-label0-group0"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
hidden-layer-1 (Dense)       (None, 10)                30        
_________________________________________________________________
logit-layer (Dense)          (None, 1)                 11        
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________
