In [14]:
import numpy as np
import pandas as pd
from test import *
import wasserstein_fairness.combined_costs as cc

In [15]:
sample_size = 1000
x_train, y_train = x_train[:sample_size], y_train[:sample_size]
data_train = pd.DataFrame(x_train), pd.DataFrame(y_train)
theta = np.random.random((40,))
group_train = group_train[:sample_size]

In [16]:
import itertools
groups = list(itertools.product([0,1], [0,1]))
groups = [list(x) for x in groups]
groups_data = [x_train[np.all(group_train == g, axis = 1)] for g in groups]
groups

[[0, 0], [0, 1], [1, 0], [1, 1]]

In [4]:
a = cc.gradient_smoothed_logistic(data_train, groups_data, theta= theta, alpha = 0.5, beta = 1e-2, lambda_=1e-1)

[[-0.08780328 -0.08751966 -0.08781799 ... -0.08885901 -0.08781439
  -0.08947271]
 [-0.13529991 -0.13542561 -0.13529339 ... -0.13483203 -0.13529499
  -0.13456006]
 [-0.09769798 -0.09855674 -0.09765344 ... -0.09450143 -0.09766433
  -0.09264328]
 ...
 [ 0.08887236  0.09070898  0.08877711 ...  0.08203593  0.0888004
   0.07806192]
 [ 0.03168607  0.03267935  0.03163456 ...  0.02798882  0.03164716
   0.02583961]
 [ 0.71747308  0.7362141   0.71650113 ...  0.64771357  0.71673882
   0.60716241]]
[ 1.79527035e-01  6.44763452e-02  1.80602703e-02  2.72570514e-02
  1.57250146e-01  6.04058644e-04 -2.53875686e-03 -1.09516087e-01
 -4.27130917e-04 -3.32381656e-03 -6.91937834e-04  0.00000000e+00
 -3.87702672e-03  4.51780745e-06 -5.48469564e-03 -3.93557879e-04
 -1.02299169e-01 -4.74188189e-03  8.98142002e-04 -2.52689360e-02
  0.00000000e+00 -2.80259569e-03 -3.46737614e-03 -6.48278055e-04
 -1.66226784e-02 -2.78239038e-03 -4.34495814e-02 -1.11313298e-03
  1.40868560e-03 -2.54029370e-03 -1.71233815e-02 -1.49

In [6]:
a[0].shape, a[1].shape

((40, 1000), (40,))

In [7]:
x_train.shape[1]

39

In [3]:
x_train[np.all(group_train == [0, 1], axis = 1)]

array([[ 1.02285308, -0.04535909, -0.14741329, ...,  0.        ,
         0.        ,  0.        ],
       [-0.49331214, -0.82620885, -0.14741329, ...,  0.        ,
         0.        ,  1.        ],
       [ 1.40189439, -3.16875812, -0.14741329, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.26477047,  1.51634043,  1.72435028, ...,  0.        ,
         0.        ,  0.        ],
       [-1.25139475, -0.04535909, -0.14741329, ...,  1.        ,
         0.        ,  0.        ],
       [ 0.34057873,  1.12591555, -0.14741329, ...,  0.        ,
         0.        ,  1.        ]])

In [8]:
group_train == [0,1]

array([[ True,  True],
       [ True, False],
       [ True, False],
       ...,
       [ True, False],
       [False,  True],
       [False, False]])

In [2]:
import shelve
filename='shelve.out'
my_shelf = shelve.open(filename,'n') # 'n' for new

for key in dir():
    try:
        my_shelf[key] = globals()[key]
    except TypeError:
        #
        # __builtins__, my_shelf, and imported modules can not be shelved.
        #
        print('ERROR shelving: {0}'.format(key))
my_shelf.close()

ERROR shelving: __builtin__
ERROR shelving: __builtins__
ERROR shelving: cc


PicklingError: Can't pickle <built-in function input>: it's not the same object as builtins.input

In [5]:
globals().keys()


dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', '_', '__', '___', 'os', 'sys', '_i', '_ii', '_iii', '_i1', 'np', 'pd', 'tf', 'preprocess_adult_data', 'seed', 'dataset_orig_train', 'dataset_orig_test', 'all_train', 'all_test', 'y_train', 'y_test', 'x_train', 'x_test', 'group_train', 'group_test', 'cc', '_rwho_ls', '_VSCODE_targetVariable', '_VSCODE_evalResult', '_i2', 'shelve', 'filename', 'my_shelf', 'key', '_i3', '_3', '_i4', '_4', '_i5'])

KeysView(<shelve.DbfilenameShelf object at 0x14630d450>)

In [7]:
b = np.array([[1, 2], [3, 4], [5, 6]])
b.shape

(3, 2)

In [9]:
np.mean(b, axis = 1)

array([1.5, 3.5, 5.5])

In [12]:
c = np.clip(b, 1, 2)

In [13]:
c

array([[1, 2],
       [2, 2],
       [2, 2]])

In [1]:
from test import *

In [2]:
e = unit_expt()
e.fit(data_train, data_test)

Test accuracy for step 0: 0.2569375345494748

Test GAP RMS for gender and step 0: 0.007125788586082452

Test GAP RMS for race and step 0: 0.008213065307743793

Test balanced accuracy for step 0: 0.509129418638621


Test accuracy for step 250: 0.2677722498618021

Test GAP RMS for gender and step 250: 0.015337586968614786

Test GAP RMS for race and step 250: 0.013123608025617926

Test balanced accuracy for step 250: 0.5162868828513001


Test accuracy for step 500: 0.2809286898839138

Test GAP RMS for gender and step 500: 0.029044393527943493

Test GAP RMS for race and step 500: 0.012867315948242891

Test balanced accuracy for step 500: 0.5248237486643399


Test accuracy for step 750: 0.30005527915975677

Test GAP RMS for gender and step 750: 0.04045016650289563

Test GAP RMS for race and step 750: 0.016363207688183085

Test balanced accuracy for step 750: 0.5373045233292641


Test accuracy for step 1000: 0.3263681592039801

Test GAP RMS for gender and step 1000: 0.05316580765304288

Test